### ISSUE TITLE
Custom DamageTypes

### ISSUE THREAD

**Issue by gabizou** [Atherys-Horizons/AtherysRPG#1]
Heya, just wanted to make it aware that your custom damage types are not being registered with Sponge's DamageType registry module, and this may not seem much like a problem, it would become a problem when those damage types are being looked up from other plugins not depending on AtherysRPG.

More specifically, I've noticed that you have your own [registry module](https://github.com/Atherys-Horizons/AtherysRPG/blob/master/src/main/java/com/atherys/rpg/api/damage/AtherysDamageTypeRegistry.java) for your damage types, but ideally, what you'd be doing is having the following in your main plugin's class:

```java
@Listener
public void onDamageTypeRegistration(GameRegistryEvent.Register<DamageType> event) {
   event.register(AtherysDamageTypes.FOO);
  // continue registering, just like you do for your modules.
}
```

Of course, this doesn't change that if you perform a lookup of the custom damage type, your custom damage types would be looked up through the default interface `DamageType` and then type casted to `AtherysDamageType`.

**Comment by HaedHutner** [comment]
Thanks for the feedback! :D The fact that AtherysDamageType implements DamageType is something of a leftover from an earlier stage of the system. Currently, atherys damage types aren't really used when building damage sources, so it would be all the same if they didn't even implement the sponge damage type interface. They're mostly used for configuring different ways in which damage can be calculated using expressions.
