### ISSUE TITLE
Resource-regen-calculation from config is not working

### ISSUE THREAD

**Issue by cicetil** [Atherys-Horizons/AtherysRPG#23]
Resource regeneration should be at +1/s based on the calculation in the config. Attributes should also affect the regen rate.
However, resources are currently regenerating at +5/s and a player's attributes have no affect on the rate.
You can test this by simply using a skill, and seeing the resource regenerate.

**Comment by HaedHutner** [comment]
Fixed in https://github.com/Atherys-Horizons/AtherysSkills/commit/d42d30c9c4cccea3af175dd9aed8349f3f14fc11
